apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-app
  namespace: default
spec:
  replicas: 5
  selector:
    matchLabels:
      app: ecommerce-app
  template:
    metadata:
      labels:
        app: ecommerce-app
    spec:
      containers:
      - name: ecommerce-app
        image: venkiaws/E-commerce-py-app:latest
        ports:
        - containerPort: 5000
